import type { Agent, AgentEvent } from './types'

export const SEED_AGENTS: Agent[] = [
  {
    id: 'agent-cipher',
    name: 'Cipher',
    model: 'groq/llama-3.3-70b-versatile',
    avatarSeed: 'ciph-7a2f',
    createdAt: '2025-10-01T00:00:00Z',
    status: 'active',
    authorization: {
      budgetUsdc: 500,
      perTxLimitUsdc: 50,
      expiresAt: '2026-12-31T23:59:59Z',
      categories: ['data-apis', 'compute', 'agent-services'],
      network: 'arbitrum-one',
    },
  },
  {
    id: 'agent-nova',
    name: 'Nova',
    model: 'groq/llama-3.1-8b-instant',
    avatarSeed: 'nova-3c8d',
    createdAt: '2025-11-15T00:00:00Z',
    status: 'active',
    authorization: {
      budgetUsdc: 200,
      perTxLimitUsdc: 25,
      expiresAt: '2026-12-31T23:59:59Z',
      categories: ['compute', 'storage'],
      network: 'arbitrum-one',
    },
  },
  {
    id: 'agent-lyra',
    name: 'Lyra',
    model: 'heurist/mistral-7b-instruct',
    avatarSeed: 'lyra-9e1b',
    createdAt: '2025-12-01T00:00:00Z',
    status: 'active',
    authorization: {
      budgetUsdc: 100,
      perTxLimitUsdc: 15,
      expiresAt: '2026-12-31T23:59:59Z',
      categories: ['data-apis', 'storage'],
      network: 'arbitrum-sepolia',
    },
  },
  {
    id: 'agent-orion',
    name: 'Orion',
    model: 'heurist/mistral-7b-instruct',
    avatarSeed: 'orion-2d5c',
    createdAt: '2025-12-10T00:00:00Z',
    status: 'active',
    authorization: {
      budgetUsdc: 75,
      perTxLimitUsdc: 10,
      expiresAt: '2026-12-31T23:59:59Z',
      categories: ['compute'],
      network: 'arbitrum-sepolia',
    },
  },
  {
    id: 'agent-sage',
    name: 'Sage',
    model: 'heurist/mistral-7b-instruct',
    avatarSeed: 'sage-6f3a',
    createdAt: '2025-12-20T00:00:00Z',
    status: 'active',
    authorization: {
      budgetUsdc: 50,
      perTxLimitUsdc: 8,
      expiresAt: '2026-12-31T23:59:59Z',
      categories: ['data-apis'],
      network: 'arbitrum-sepolia',
    },
  },
]

export const SEED_EVENTS: AgentEvent[] = [
  // Atlas — 20 events, clean record → AAA ~93
  ...Array.from({ length: 18 }, (_, i) => ({
    id: `atlas-ps-${i}`,
    agentId: 'agent-cipher',
    kind: 'payment_success' as const,
    label: `USDC transfer to data provider #${i + 1}`,
    at: new Date(Date.now() - (20 - i) * 86400000).toISOString(),
    amountUsdc: 12 + (i % 5) * 3,
    category: 'data-apis' as const,
    txHash: `0xatlas${i.toString(16).padStart(6, '0')}`,
    trustDelta: 0.8,
  })),
  ...Array.from({ length: 6 }, (_, i) => ({
    id: `atlas-tc-${i}`,
    agentId: 'agent-cipher',
    kind: 'task_completed' as const,
    label: `Market analysis report #${i + 1}`,
    at: new Date(Date.now() - (18 - i * 3) * 86400000).toISOString(),
    trustDelta: 1.2,
  })),

  // Prism — 14 events, mostly clean → A ~78
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `prism-ps-${i}`,
    agentId: 'agent-nova',
    kind: 'payment_success' as const,
    label: `Compute job payment #${i + 1}`,
    at: new Date(Date.now() - (15 - i) * 86400000).toISOString(),
    amountUsdc: 8 + (i % 4) * 2,
    category: 'compute' as const,
    txHash: `0xprism${i.toString(16).padStart(6, '0')}`,
    trustDelta: 0.6,
  })),
  {
    id: 'prism-pf-0',
    agentId: 'agent-nova',
    kind: 'payment_failed',
    label: 'RPC timeout on compute node',
    at: new Date(Date.now() - 5 * 86400000).toISOString(),
    amountUsdc: 15,
    category: 'compute',
    trustDelta: -2.1,
  },
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `prism-tc-${i}`,
    agentId: 'agent-nova',
    kind: 'task_completed' as const,
    label: `Embedding batch #${i + 1}`,
    at: new Date(Date.now() - (10 - i * 2) * 86400000).toISOString(),
    trustDelta: 1.0,
  })),

  // Vox — 8 events, recently promoted → BBB ~68
  ...Array.from({ length: 6 }, (_, i) => ({
    id: `vox-ps-${i}`,
    agentId: 'agent-lyra',
    kind: 'payment_success' as const,
    label: `Storage write #${i + 1}`,
    at: new Date(Date.now() - (10 - i) * 86400000).toISOString(),
    amountUsdc: 4 + i,
    category: 'storage' as const,
    txHash: `0xvox${i.toString(16).padStart(6, '0')}`,
    trustDelta: 0.5,
  })),
  {
    id: 'vox-pf-0',
    agentId: 'agent-lyra',
    kind: 'payment_failed',
    label: 'Insufficient gas estimate',
    at: new Date(Date.now() - 4 * 86400000).toISOString(),
    amountUsdc: 8,
    category: 'storage',
    trustDelta: -1.8,
  },
  {
    id: 'vox-tc-0',
    agentId: 'agent-lyra',
    kind: 'task_completed',
    label: 'IPFS pinning batch complete',
    at: new Date(Date.now() - 2 * 86400000).toISOString(),
    trustDelta: 0.9,
  },

  // Echo — 5 events, rebuilding → BB ~60
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `echo-ps-${i}`,
    agentId: 'agent-orion',
    kind: 'payment_success' as const,
    label: `LLM inference call #${i + 1}`,
    at: new Date(Date.now() - (8 - i * 2) * 86400000).toISOString(),
    amountUsdc: 5,
    category: 'compute' as const,
    txHash: `0xecho${i.toString(16).padStart(6, '0')}`,
    trustDelta: 0.4,
  })),
  {
    id: 'echo-pf-0',
    agentId: 'agent-orion',
    kind: 'payment_failed',
    label: 'Wallet nonce conflict',
    at: new Date(Date.now() - 6 * 86400000).toISOString(),
    amountUsdc: 10,
    category: 'compute',
    trustDelta: -2.5,
  },
  {
    id: 'echo-lb-0',
    agentId: 'agent-orion',
    kind: 'limit_blocked',
    label: 'Exceeded per-tx limit of $10',
    at: new Date(Date.now() - 3 * 86400000).toISOString(),
    amountUsdc: 15,
    category: 'compute',
    trustDelta: -3.0,
  },

  // Kael — 4 events, multiple blocks → B ~47
  {
    id: 'kael-ps-0',
    agentId: 'agent-sage',
    kind: 'payment_success',
    label: 'Oracle query fee',
    at: new Date(Date.now() - 7 * 86400000).toISOString(),
    amountUsdc: 3,
    category: 'data-apis',
    txHash: '0xkael000001',
    trustDelta: 0.3,
  },
  {
    id: 'kael-pf-0',
    agentId: 'agent-sage',
    kind: 'payment_failed',
    label: 'Contract revert: unauthorized',
    at: new Date(Date.now() - 5 * 86400000).toISOString(),
    amountUsdc: 8,
    category: 'data-apis',
    trustDelta: -3.2,
  },
  {
    id: 'kael-lb-0',
    agentId: 'agent-sage',
    kind: 'limit_blocked',
    label: 'Attempted $20 tx (limit: $8)',
    at: new Date(Date.now() - 4 * 86400000).toISOString(),
    amountUsdc: 20,
    category: 'data-apis',
    trustDelta: -3.5,
  },
  {
    id: 'kael-lb-1',
    agentId: 'agent-sage',
    kind: 'limit_blocked',
    label: 'Attempted $15 tx (limit: $8)',
    at: new Date(Date.now() - 2 * 86400000).toISOString(),
    amountUsdc: 15,
    category: 'data-apis',
    trustDelta: -3.5,
  },
]

export const SEED_DELEGATIONS: Array<{ from: string; to: string }> = [
  { from: 'agent-cipher', to: 'agent-nova' },
  { from: 'agent-cipher', to: 'agent-lyra' },
  { from: 'agent-nova', to: 'agent-orion' },
]
